In [70]:
import pandas as pd
import cv2
import torch
from model.model_poseformerv2 import Model

df = pd.read_json('../MediaPipe_landmarks/squat_back_res_landmarks.json')
df

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,"{'frame': 6, 'id': 0, 'x': 0.463299334049224, ...","{'frame': 6, 'id': 1, 'x': 0.45618325471878, '...","{'frame': 6, 'id': 2, 'x': 0.456037521362304, ...","{'frame': 6, 'id': 3, 'x': 0.45609679818153304...","{'frame': 6, 'id': 4, 'x': 0.456426203250885, ...","{'frame': 6, 'id': 5, 'x': 0.45641583204269404...","{'frame': 6, 'id': 6, 'x': 0.45636120438575706...","{'frame': 6, 'id': 7, 'x': 0.46162694692611606...","{'frame': 6, 'id': 8, 'x': 0.46121793985366805...","{'frame': 6, 'id': 9, 'x': 0.47057688236236506...",...,"{'frame': 6, 'id': 23, 'x': 0.6501501798629761...","{'frame': 6, 'id': 24, 'x': 0.645352125167846,...","{'frame': 6, 'id': 25, 'x': 0.7627992630004881...","{'frame': 6, 'id': 26, 'x': 0.758358895778656,...","{'frame': 6, 'id': 27, 'x': 0.8846518993377681...","{'frame': 6, 'id': 28, 'x': 0.872469007968902,...","{'frame': 6, 'id': 29, 'x': 0.90949523448944, ...","{'frame': 6, 'id': 30, 'x': 0.8951395750045771...","{'frame': 6, 'id': 31, 'x': 0.858225405216217,...","{'frame': 6, 'id': 32, 'x': 0.8564399480819701..."
1,"{'frame': 7, 'id': 0, 'x': 0.46320304274559004...","{'frame': 7, 'id': 1, 'x': 0.45603865385055503...","{'frame': 7, 'id': 2, 'x': 0.45593577623367304...","{'frame': 7, 'id': 3, 'x': 0.45601740479469305...","{'frame': 7, 'id': 4, 'x': 0.45618787407875006...","{'frame': 7, 'id': 5, 'x': 0.45614814758300704...","{'frame': 7, 'id': 6, 'x': 0.45605915784835804...","{'frame': 7, 'id': 7, 'x': 0.46141320466995206...","{'frame': 7, 'id': 8, 'x': 0.46071049571037204...","{'frame': 7, 'id': 9, 'x': 0.47051328420639005...",...,"{'frame': 7, 'id': 23, 'x': 0.6513125896453851...","{'frame': 7, 'id': 24, 'x': 0.646645307540893,...","{'frame': 7, 'id': 25, 'x': 0.763038694858551,...","{'frame': 7, 'id': 26, 'x': 0.7586061358451841...","{'frame': 7, 'id': 27, 'x': 0.8846474885940551...","{'frame': 7, 'id': 28, 'x': 0.872238993644714,...","{'frame': 7, 'id': 29, 'x': 0.9092770814895631...","{'frame': 7, 'id': 30, 'x': 0.8983764052391051...","{'frame': 7, 'id': 31, 'x': 0.858960568904876,...","{'frame': 7, 'id': 32, 'x': 0.854632794857025,..."
2,"{'frame': 8, 'id': 0, 'x': 0.46320304274559004...","{'frame': 8, 'id': 1, 'x': 0.45606032013893105...","{'frame': 8, 'id': 2, 'x': 0.45598092675209, '...","{'frame': 8, 'id': 3, 'x': 0.456078082323074, ...","{'frame': 8, 'id': 4, 'x': 0.456143170595169, ...","{'frame': 8, 'id': 5, 'x': 0.45602712035179105...","{'frame': 8, 'id': 6, 'x': 0.45581617951393105...","{'frame': 8, 'id': 7, 'x': 0.46141374111175504...","{'frame': 8, 'id': 8, 'x': 0.460113227367401, ...","{'frame': 8, 'id': 9, 'x': 0.470540165901184, ...",...,"{'frame': 8, 'id': 23, 'x': 0.65151047706604, ...","{'frame': 8, 'id': 24, 'x': 0.6469734907150261...","{'frame': 8, 'id': 25, 'x': 0.763149380683898,...","{'frame': 8, 'id': 26, 'x': 0.7586321234703061...","{'frame': 8, 'id': 27, 'x': 0.8846324086189271...","{'frame': 8, 'id': 28, 'x': 0.871872246265411,...","{'frame': 8, 'id': 29, 'x': 0.909133970737457,...","{'frame': 8, 'id': 30, 'x': 0.8997356295585631...","{'frame': 8, 'id': 31, 'x': 0.859165906906127,...","{'frame': 8, 'id': 32, 'x': 0.8536185026168821..."
3,"{'frame': 9, 'id': 0, 'x': 0.46321669220924305...","{'frame': 9, 'id': 1, 'x': 0.45611098408699, '...","{'frame': 9, 'id': 2, 'x': 0.456058651208877, ...","{'frame': 9, 'id': 3, 'x': 0.45617115497589106...","{'frame': 9, 'id': 4, 'x': 0.456130623817443, ...","{'frame': 9, 'id': 5, 'x': 0.455966830253601, ...","{'frame': 9, 'id': 6, 'x': 0.45567867159843406...","{'frame': 9, 'id': 7, 'x': 0.46141043305397006...","{'frame': 9, 'id': 8, 'x': 0.459774404764175, ...","{'frame': 9, 'id': 9, 'x': 0.47065597772598206...",...,"{'frame': 9, 'id': 23, 'x': 0.651659965515136,...","{'frame': 9, 'id': 24, 'x': 0.647133409976959,...","{'frame': 9, 'id': 25, 'x': 0.763355493545532,...","{'frame': 9, 'id': 26, 'x': 0.759326517581939,...","{'frame': 9, 'id': 27, 'x': 0.884617805480957,...","{'frame': 9, 'id': 2

In [71]:
df.shape

(416, 33)

In [72]:
def count_frames(video_path):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise ValueError("Could not open video file.")

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    cap.release()
    return total_frames

video_path = "../../ProcessedVideos/squat_back_res.mp4"
print("Frame count:", count_frames(video_path))


Frame count: 421


In [73]:
# Correct OPT config for this checkpoint
class Opt:
    layers = 4                   # #Depth = 4
    number_of_kept_frames = 27   # n = 27
    number_of_kept_coeffs = 27   # same as n
    naive = False                # depends on baseline design; default False


opt = Opt()

# Instantiate model
model = Model(opt, num_frame=243, num_joints=17, in_chans=2)
model.eval()

# Load checkpoint
ckpt = torch.load("Checkpoints/27_243_45.2.bin", map_location="cpu")
state_dict = ckpt["model_pos"]

# Remove "module." prefix if it exists
new_state_dict = {k.replace("module.", ""): v for k, v in state_dict.items()}

# Load weights
missing, unexpected = model.load_state_dict(new_state_dict, strict=False)
print("Missing keys:", missing)
print("Unexpected keys:", unexpected)
print("🎉 Weights loaded successfully!")


Missing keys: []
Unexpected keys: []
🎉 Weights loaded successfully!


In [74]:
for k in new_state_dict.keys():
    if 'blocks' in k:
        print(k.split('.')[1])


0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3


In [75]:
import json
import numpy as np

with open('../MediaPipe_landmarks/squat_back_res_new_landmarks.json', "r") as f:
    data = json.load(f)

# Convert to numpy
frames = []
for frame in data:
    frame_coords = []
    for lm in frame:
        frame_coords.append([lm['x'], lm['y']])
    frames.append(frame_coords)

arr = np.array(frames)   # shape = (T, 33, 3)


In [76]:
arr.shape

(416, 33, 2)

In [77]:
import numpy as np

# keypoints shape (416, 33, 2)
new_arr = arr  # replace with your loaded array

# indices you want to remove
drop = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 17, 18, 19, 20, 21, 22}

# indices you want to keep
keep = [i for i in range(33) if i not in drop]

# Reduce array from (416, 33, 2) → (416, 17, 2)
reduced = new_arr[:, keep, :]
reduced.shape

(416, 17, 2)

In [78]:
_reduced = reduced[:243, :, :]
reduced.shape

(416, 17, 2)

In [79]:
reduced = np.expand_dims(reduced, axis=0)
reduced.shape

(1, 416, 17, 2)

In [80]:
import torch
import numpy as np

# arr is your numpy array with shape (1, 243, 17, 2)
inp = torch.tensor(reduced, dtype=torch.float32)

In [81]:
inp.shape

torch.Size([1, 416, 17, 2])

In [82]:
inp = inp.permute(0, 3, 1, 2)
inp = inp.unsqueeze(-1)
inp.shape

torch.Size([1, 2, 416, 17, 1])

In [83]:
with torch.no_grad():
    pose_3d, embedding = model(inp)   # shape: (1, 17, 2, 243, 1)


In [84]:
print(len(pose_3d))
print(pose_3d)


1
tensor([[[[[-1.2942e-04],
           [-6.1287e-02],
           [-6.0187e-04],
           [ 7.6267e-02],
           [ 6.1289e-02],
           [ 9.6216e-03],
           [-2.3248e-03],
           [ 1.6144e-01],
           [ 2.9540e-01],
           [ 2.8814e-01],
           [ 3.2128e-01],
           [ 3.2816e-01],
           [ 5.1701e-01],
           [ 5.2878e-01],
           [ 3.4756e-01],
           [ 4.8330e-01],
           [ 4.7796e-01]]],


         [[[ 6.7001e-05],
           [ 6.8570e-02],
           [-8.8879e-03],
           [ 1.7600e-01],
           [-6.8569e-02],
           [ 1.6828e-01],
           [-2.0285e-02],
           [-2.9582e-02],
           [-1.0117e-01],
           [-8.3363e-02],
           [-1.8799e-01],
           [-6.4356e-02],
           [-1.2750e-01],
           [ 8.5159e-02],
           [-1.1570e-01],
           [ 5.4663e-02],
           [-1.4041e-01]]],


         [[[-5.7190e-05],
           [-1.7345e-02],
           [-1.0981e-01],
           [ 7.5371e-02],
  

In [85]:
print(len(embedding[0][0]))
print(embedding[0][0])

1088
tensor([ 0.0021,  0.0066,  0.0010,  ..., -0.0113, -0.0061, -0.0009])


In [86]:
torch.save(embedding, 'squat_back_res_new_embedding.pt')

In [96]:
emb = torch.load('squat_back_res_embedding.pt')
emb_new = torch.load('squat_back_res_new_embedding.pt')

similarity = torch.cosine_similarity(emb, emb_new, dim=-1)
print(similarity)

tensor([[0.9343]])
